trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: |
    dotnet restore
    dotnet build
  displayName: 'Build'

- task: CavissonCodeAnalyzer@1
  inputs:
    cavissonAnalyzerServiceConnection: 'cav1'
    project: 'eShopOnWeb'